#!/bin/sh
# Setup a machine for Sublime Text

# Replace Icon
cp "$DOTFILES/sublime/Sublime Text.icns" '/Applications/Sublime Text.app/Contents/Resources/Sublime Text.icns'

# symlink settings in
SUBLIME_DIR="$HOME/Library/Application Support/Sublime Text 3/Packages"
SUBLIME_USER_DIR="$SUBLIME_DIR/User"
SUBLIME_BACKUP_DIR="$SUBLIME_DIR/User.backup"

if [ -L "$SUBLIME_USER_DIR" ]; then
  # Relink
  rm "$SUBLIME_USER_DIR"
  ln -s "$DOTFILES/sublime/User" "$SUBLIME_USER_DIR"
else
  if [ -d "$SUBLIME_BACKUP_DIR" ]; then
    # Erase the User dir if we already have a backup
    rm -rf "$SUBLIME_USER_DIR"
  else
    # Backup the folder
    mv "$SUBLIME_USER_DIR" "$SUBLIME_BACKUP_DIR"
  fi
  ln -s "$DOTFILES/sublime/User" "$SUBLIME_USER_DIR"
fi

# Add Automator service
cp -r "$DOTFILES/sublime/Open in Sublime.workflow" "$HOME/Library/Services"
