#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

# Replace Icon
curl -s 'https://raw.github.com/dmatarazzo/Sublime-Text-2-Icon/master/Sublime%20Text%202.icns' --output '/Applications/Sublime Text 2.app/Contents/Resources/Sublime Text 2.icns'

# symlink settings in
sublime_dir="$HOME/Library/Application Support/Sublime Text 2/Packages"
if [ -d "$sublime_dir/User.backup" ]; then
	rm -rf "$sublime_dir/User.backup"
fi
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$DOTFILES/sublime2/User" "$sublime_dir"

# Add Automator service
cp -r "$DOTFILES/sublime2/Open in Sublime.workflow" "$HOME/Library/Services"
