#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

# Replace Icon
curl https://github.com/dmatarazzo/Sublime-Text-2-Icon/raw/master/Sublime%20Text%202.icns --output /Applications/Sublime\ Text\ 2.app/Contents/Resources/Sublime\ Text\ 2.icns

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 2/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSH/sublime2/User" "$sublime_dir"

# Add Automator service
cp -r "$ZSH/sublime2/Open\ in\ Sublime.workflow" "~/Library/Services"
